spring:

  application:
    name: TransportSchedule

  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    url: ${SPRING_DATASOURCE_URL}

  data:
    redis:
      port: 6379
      host: redis


  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true  # Форматирование SQL-запросов для читаемости
        show_sql: true  # Вывод SQL-запросов в лог
        use_sql_comments: true  # Добавляет комментарии Hibernate в логи

logging:
  level:
    root: info
    org.springframework: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
    org.example.transportschedule: DEBUG
  file:
    name: logs/application.log


springdoc:
  swagger-ui:
    path: /swagger-ui.html
